[package]
name = "elm-parser"
version = "0.1.0"
authors = ["Michael Jones <michael@zaptic.com>"]

[[bin]]
name = "elm-parser-dump"
path = "src/dump.rs"

[dependencies]
combine = "3.6.1"
regex = { version = "^1.0" }
walkdir = "2"
clap = "2.32.0"
