[package]
name = "elm-parser"
version = "0.1.0"
authors = ["Michael Jones <michael@zaptic.com>"]

[dependencies]
nom = { version = "4.0.0", features = ["regexp", "verbose-errors"] }
# nom = { git = "https://github.com/geal/nom", features = ["verbose-errors"] }
regex = { version = "^1.0" }
