[package]
name = "elm-parser"
version = "0.1.0"
authors = ["Michael Jones <michael@zaptic.com>"]

[build-dependencies]
lalrpop = { version = "0.19", features = ["lexer"] }

[dependencies]
lalrpop-util = "0.19.0"
regex = "1"
